### ISSUE TITLE
Does not work from within a repo

### ISSUE THREAD

**Issue by xcambar** [xcambar/purs#1]
The prompt shows the correct git info only when at the root of the repo.

**Comment by nkoehring** [comment]
@xcambar that will be fixed by my PR

**Comment by xcambar** [comment]
Unless I screwed up, I don'didn't notice the fix in the current master.
Can you elaborate?

**Comment by nkoehring** [comment]
Sorry, I need to correct. Will be fixed by my **future** PR. https://github.com/xcambar/purs/pull/12
