### ISSUE TITLE
Git status in new repos fails

### ISSUE THREAD

**Issue by jbolila** [xcambar/purs#7]
How to reproduce:

```bash
cargo new proj
cd proj
```

Error:

```text
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: -9, klass: 4, message: "reference \'refs/heads/master\' not found" }', /checkout/src/libcore/result.rs:906:4
```

the issue occurs in [src/precmd.rs#L34](https://github.com/xcambar/purs/blob/master/src/precmd.rs#L34).

btw great idea!! thank you for starting this.

**Comment by xcambar** [comment]
I can close now. Thanks again!
